// Auto-generated by scripts/book-register.js. Do not edit by hand.
import type { BookRegistry } from './types';

export const REGISTRY: BookRegistry = {
  titles: [

  ],
  readingsByTitleId: {

  },
  assets: {

  },
};

export function validateRegistry(): string[] {
  const errors: string[] = [];
  for (const reading of Object.values(REGISTRY.readingsByTitleId).flat()) {
    if (!REGISTRY.titles.find((t) => t.id === reading.titleId)) {
      errors.push(`Reading ${reading.id} references missing title ${reading.titleId}`);
    }
    for (const page of reading.pages) {
      if (!REGISTRY.assets[page.image]) {
        errors.push(`Reading ${reading.id} page references missing image ${page.image}`);
      }
      if (!REGISTRY.assets[page.audio]) {
        errors.push(`Reading ${reading.id} page references missing audio ${page.audio}`);
      }
    }
  }
  return errors;
}
