import { Book } from './types';

// Generated by scripts/book-register.js — do not edit by hand.
// Source of truth lives in assets/books/<book-id>/book.json and the
// asset filenames themselves. Re-run the script after adding books or readers.

export const BOOKS: Book[] = [
  {
    id: 'test',
    title: 'Test Book',
    pages: [
      require('../../assets/books/test/pages/page-01.png'),
    ],
    readers: [
      {
        id: 'ryan',
        name: 'Uncle Ryan',
        pages: [
          require('../../assets/books/test/voices/ryan/page-01.mp3'),
        ],
      },
    ],
  },
];

export function validateBooks(books: Book[]): string[] {
  const errors: string[] = [];
  const seenBookIds = new Set<string>();
  for (const book of books) {
    if (seenBookIds.has(book.id)) {
      errors.push(`Duplicate book id: "${book.id}".`);
    }
    seenBookIds.add(book.id);

    if (book.readers.length === 0) {
      errors.push(`Book "${book.id}" has no readers; at least one is required.`);
    }

    if (book.pages.length === 0) {
      errors.push(`Book "${book.id}" has no pages; at least one is required.`);
    }

    const seenReaderIds = new Set<string>();
    for (const reader of book.readers) {
      if (seenReaderIds.has(reader.id)) {
        errors.push(`Duplicate reader id "${reader.id}" within book "${book.id}".`);
      }
      seenReaderIds.add(reader.id);

      if (reader.pages.length !== book.pages.length) {
        errors.push(
          `Reader "${reader.id}" in book "${book.id}" has ${reader.pages.length} audio pages but the book has ${book.pages.length} image pages.`,
        );
      }
    }
  }
  return errors;
}
